[package]
name = "idwtet"
version = "0.3.0"
entrypoint = "idwtet.typ"
authors = ["Ludwig Austermann"]
license = "MIT"
description = "Package for uniform, correct and simplified typst code demonstration."
repository = "https://github.com/ludwig-austermann/typst-idwtet"
exclude = ["examples"]
compiler = "0.8.0"

[packaging]
include = ["examples/*.typ", "examples/*.pdf"]